swagger: '2.0'
info:
  version: 0.0.1
  title: vehicle
  description: first draft
host: 'localhost:2002'
basePath: /api
schemes:
  - https
  - http
produces:
  - application/json
paths:
  /vehicles:
    get:
      tags:
        - Vehicle
      description: Gets all vehicles from the system that the user has access to
      operationId: getVehicle
      produces:
        - application/json
      x-swagger-router-controller: Vehicle
      responses:
        '200':
          description: vehicle response
          schema:
            type: array
            items:
              $ref: '#/definitions/vehicle'
        '404':
          description: vehicle response
          schema:
            type: object
        '500':
          description: vehicle response
          schema:
            type: object
      parameters:
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
    post:
      tags:
        - Vehicle
      description: Posts all vehicles from the system that the user has access to
      operationId: postVehicle
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Vehicle
      responses:
        '200':
          description: vehicle response
          schema:
            type: array
            items:
              $ref: '#/definitions/vehicle'
        '404':
          description: vehicle response
          schema:
            type: object
        '500':
          description: vehicle response
          schema:
            type: object
      parameters:
        - name: vehicles
          in: body
          schema:
            $ref: '#/definitions/vehicle'
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
  '/vehicles/{vin}':
    get:
      tags:
        - Vehicle
      description: Gets all vehicles from the system that the user has access to
      operationId: getVehicleById
      produces:
        - application/json
      x-swagger-router-controller: Vehicle
      responses:
        '200':
          description: vehicle response
          schema:
            type: object
            $ref: '#/definitions/vehicle'
        '404':
          description: vehicle response
          schema:
            type: object
        '500':
          description: vehicle response
          schema:
            type: object
      parameters:
        - name: vin
          in: path
          description: Path Parameter
          type: string
          required: true
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
    put:
      tags:
        - Vehicle
      description: Puts all vehicles from the system that the user has access to
      operationId: putVehicle
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Vehicle
      responses:
        '200':
          description: vehicle response
          schema:
            type: array
            items:
              $ref: '#/definitions/vehicle'
        '404':
          description: vehicle response
          schema:
            type: object
        '500':
          description: vehicle response
          schema:
            type: object
      parameters:
        - name: vehicles
          in: body
          schema:
            $ref: '#/definitions/vehicle'
        - name: vin
          in: path
          description: Path Parameter
          type: string
          required: true
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
    patch:
      tags:
        - Vehicle
      description: Patchs all vehicles from the system that the user has access to
      operationId: patchVehicle
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Vehicle
      responses:
        '200':
          description: vehicle response
          schema:
            type: array
            items:
              $ref: '#/definitions/vehicle'
        '404':
          description: vehicle response
          schema:
            type: object
        '500':
          description: vehicle response
          schema:
            type: object
      parameters:
        - name: vehicles
          in: body
          schema:
            $ref: '#/definitions/patchvehicle'
        - name: vin
          in: path
          description: Path Parameter
          type: string
          required: true
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
    delete:
      tags:
        - Vehicle
      description: Deletes all vehicles from the system that the user has access to
      operationId: deleteVehicle
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Vehicle
      responses:
        '204':
          description: vehicle response
          schema:
            type: array
            items:
              $ref: '#/definitions/vehicle'
        '404':
          description: vehicle response
          schema:
            type: object
        '500':
          description: vehicle response
          schema:
            type: object
      parameters:
        - name: vin
          in: path
          description: Path Parameter
          type: string
          required: true
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
definitions:
  ApiError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  vehicle:
    type: object
    properties:
      vin:
        type: string
        format: ''
      model:
        type: string
        format: ''
      year:
        type: string
        format: ''
      color:
        type: string
        format: ''
    required:
      - vin
      - model
      - year
  patchvehicle:
    type: object
    properties:
      model:
        type: string
        format: ''
      year:
        type: string
        format: ''
      color:
        type: string
        format: ''
responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: '#/definitions/ApiError'
  PersonDoesNotExistResponse:
    description: Person does not exist.
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  gateway: datapower-gateway
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:8080'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
          tls-profile: ''
          secure-gateway: false
    catch: []
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
security:
  - Bearer: []
