swagger: '2.0'
info:
  version: 0.0.1
  title: employee
  description: First draft version of API for Employee Information
host: 'localhost:2002'
basePath: /api
schemes:
  - https
  - http
produces:
  - application/json
paths:
  /Employees:
    get:
      tags:
        - Employee
      description: Gets all Employees from the system that the user has access to
      operationId: getEmployee
      produces:
        - application/json
      x-swagger-router-controller: Employee
      responses:
        '200':
          description: Employee response
          schema:
            type: array
            items:
              $ref: '#/definitions/Employee'
        '404':
          description: Employee response
          schema:
            type: object
        '500':
          description: Employee response
          schema:
            type: object
      parameters:
        - name: pageSize
          in: query
          description: Number of records returned
          type: integer
        - name: pageNumber
          in: query
          description: Page number
          type: integer
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
        - name: id
          in: query
          description: Employee id to be retrieved
          required: true
          type: string
    post:
      tags:
        - Employee
      description: Posts all Employees from the system that the user has access to
      operationId: postEmployee
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Employee
      responses:
        '200':
          description: Employee response
          schema:
            type: array
            items:
              $ref: '#/definitions/Employee'
        '404':
          description: Employee response
          schema:
            type: object
        '500':
          description: Employee response
          schema:
            type: object
      parameters:
        - name: Employees
          in: body
          schema:
            $ref: '#/definitions/Employee'
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
        - name: id
          in: query
          description: ''
          required: true
          type: string
  '/Employees/{empid}':
    get:
      tags:
        - Employee
      description: Gets all Employees from the system that the user has access to
      operationId: getEmployeeById
      produces:
        - application/json
      x-swagger-router-controller: Employee
      responses:
        '200':
          description: Employee response
          schema:
            type: object
            $ref: '#/definitions/Employee'
        '404':
          description: Employee response
          schema:
            type: object
        '500':
          description: Employee response
          schema:
            type: object
      parameters:
        - name: empid
          in: path
          description: Path Parameter
          type: string
          required: true
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
        - name: id
          in: query
          description: Employee id to be retrieved
          required: true
          type: string
    put:
      tags:
        - Employee
      description: Puts all Employees from the system that the user has access to
      operationId: putEmployee
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Employee
      responses:
        '200':
          description: Employee response
          schema:
            type: array
            items:
              $ref: '#/definitions/Employee'
        '404':
          description: Employee response
          schema:
            type: object
        '500':
          description: Employee response
          schema:
            type: object
      parameters:
        - name: Employees
          in: body
          schema:
            $ref: '#/definitions/Employee'
        - name: empid
          in: path
          description: Path Parameter
          type: string
          required: true
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
        - name: id
          in: query
          description: ''
          required: true
          type: string
    delete:
      tags:
        - Employee
      description: Deletes all Employees from the system that the user has access to
      operationId: deleteEmployee
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Employee
      responses:
        '204':
          description: Employee response
          schema:
            type: array
            items:
              $ref: '#/definitions/Employee'
        '404':
          description: Employee response
          schema:
            type: object
        '500':
          description: Employee response
          schema:
            type: object
      parameters:
        - name: empid
          in: path
          description: Path Parameter
          type: string
          required: true
        - name: revision
          in: header
          description: Needed Revision
          required: true
          type: string
          default: R1
        - name: id
          in: query
          description: ''
          required: true
          type: string
definitions:
  ApiError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  Employee:
    type: object
    properties:
      empid:
        type: string
        format: ''
      name:
        type: string
        format: ''
      age:
        type: integer
        format: int32
      city:
        type: string
        format: ''
    required:
      - empid
      - name
      - age
  patchEmployee:
    type: object
    properties:
      name:
        type: string
        format: ''
      age:
        type: integer
        format: int32
      city:
        type: string
        format: ''
responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: '#/definitions/ApiError'
  PersonDoesNotExistResponse:
    description: Person does not exist.
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  gateway: datapower-gateway
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:8080'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
          tls-profile: ''
          secure-gateway: false
    catch: []
